/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ClassClassIdRouteImport } from './routes/class.$classId'
import { Route as ResultTestIdRouteImport } from './routes/result.$testId'
import { Route as ClassClassIdIndexRouteImport } from './routes/class.$classId.index'
import { Route as ClassClassIdSubjectRouteImport } from './routes/class.$classId.$subject'
import { Route as ClassClassIdSubjectIndexRouteImport } from './routes/class.$classId.$subject.index'
import { Route as ClassClassIdSubjectChapterRouteImport } from './routes/class.$classId.$subject.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdRoute = ClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultTestIdRoute = ResultTestIdRouteImport.update({
  id: '/result/$testId',
  path: '/result/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdIndexRoute = ClassClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassClassIdRoute,
} as any)
const ClassClassIdSubjectRoute = ClassClassIdSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => ClassClassIdRoute,
} as any)
const ClassClassIdSubjectIndexRoute =
  ClassClassIdSubjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClassClassIdSubjectRoute,
  } as any)
const ClassClassIdSubjectChapterRoute =
  ClassClassIdSubjectChapterRouteImport.update({
    id: '/$chapter',
    path: '/$chapter',
    getParentRoute: () => ClassClassIdSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/result/$testId': typeof ResultTestIdRoute
  '/class/$classId/$subject': typeof ClassClassIdSubjectRouteWithChildren
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/$subject/$chapter': typeof ClassClassIdSubjectChapterRoute
  '/class/$classId/$subject/': typeof ClassClassIdSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/result/$testId': typeof ResultTestIdRoute
  '/class/$classId': typeof ClassClassIdIndexRoute
  '/class/$classId/$subject/$chapter': typeof ClassClassIdSubjectChapterRoute
  '/class/$classId/$subject': typeof ClassClassIdSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/result/$testId': typeof ResultTestIdRoute
  '/class/$classId/$subject': typeof ClassClassIdSubjectRouteWithChildren
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/$subject/$chapter': typeof ClassClassIdSubjectChapterRoute
  '/class/$classId/$subject/': typeof ClassClassIdSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/progress'
    | '/class/$classId'
    | '/result/$testId'
    | '/class/$classId/$subject'
    | '/class/$classId/'
    | '/class/$classId/$subject/$chapter'
    | '/class/$classId/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/practice'
    | '/progress'
    | '/result/$testId'
    | '/class/$classId'
    | '/class/$classId/$subject/$chapter'
    | '/class/$classId/$subject'
  id:
    | '__root__'
    | '/'
    | '/practice'
    | '/progress'
    | '/class/$classId'
    | '/result/$testId'
    | '/class/$classId/$subject'
    | '/class/$classId/'
    | '/class/$classId/$subject/$chapter'
    | '/class/$classId/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  ClassClassIdRoute: typeof ClassClassIdRouteWithChildren
  ResultTestIdRoute: typeof ResultTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId': {
      id: '/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$testId': {
      id: '/result/$testId'
      path: '/result/$testId'
      fullPath: '/result/$testId'
      preLoaderRoute: typeof ResultTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/': {
      id: '/class/$classId/'
      path: '/'
      fullPath: '/class/$classId/'
      preLoaderRoute: typeof ClassClassIdIndexRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
    '/class/$classId/$subject': {
      id: '/class/$classId/$subject'
      path: '/$subject'
      fullPath: '/class/$classId/$subject'
      preLoaderRoute: typeof ClassClassIdSubjectRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
    '/class/$classId/$subject/': {
      id: '/class/$classId/$subject/'
      path: '/'
      fullPath: '/class/$classId/$subject/'
      preLoaderRoute: typeof ClassClassIdSubjectIndexRouteImport
      parentRoute: typeof ClassClassIdSubjectRoute
    }
    '/class/$classId/$subject/$chapter': {
      id: '/class/$classId/$subject/$chapter'
      path: '/$chapter'
      fullPath: '/class/$classId/$subject/$chapter'
      preLoaderRoute: typeof ClassClassIdSubjectChapterRouteImport
      parentRoute: typeof ClassClassIdSubjectRoute
    }
  }
}

interface ClassClassIdSubjectRouteChildren {
  ClassClassIdSubjectChapterRoute: typeof ClassClassIdSubjectChapterRoute
  ClassClassIdSubjectIndexRoute: typeof ClassClassIdSubjectIndexRoute
}

const ClassClassIdSubjectRouteChildren: ClassClassIdSubjectRouteChildren = {
  ClassClassIdSubjectChapterRoute: ClassClassIdSubjectChapterRoute,
  ClassClassIdSubjectIndexRoute: ClassClassIdSubjectIndexRoute,
}

const ClassClassIdSubjectRouteWithChildren =
  ClassClassIdSubjectRoute._addFileChildren(ClassClassIdSubjectRouteChildren)

interface ClassClassIdRouteChildren {
  ClassClassIdSubjectRoute: typeof ClassClassIdSubjectRouteWithChildren
  ClassClassIdIndexRoute: typeof ClassClassIdIndexRoute
}

const ClassClassIdRouteChildren: ClassClassIdRouteChildren = {
  ClassClassIdSubjectRoute: ClassClassIdSubjectRouteWithChildren,
  ClassClassIdIndexRoute: ClassClassIdIndexRoute,
}

const ClassClassIdRouteWithChildren = ClassClassIdRoute._addFileChildren(
  ClassClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  ClassClassIdRoute: ClassClassIdRouteWithChildren,
  ResultTestIdRoute: ResultTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
